Traceback (most recent call last):
  File "box_print.py", line 37, in <module>
    raise Exception("ERROR")
Exception: ERROR
